// Bootstrap (doc 02): one-off read-only scan of an existing canonical tree
// producing genre-map.yaml, label-map.yaml and naming-variants-report.md.
// Layout assumption: <tree>/<[Collection]>/<Artist>/<release dirs> with flat
// release dirs (or slot dirs like "[Releases]") parsed by grammar.

import { readdirSync, statSync } from "node:fs";
import { join } from "node:path";
import { parseDirName } from "./naming.ts";
import type { GenreMap, LabelMap } from "./rules.ts";
import { isJunkDir, round2 } from "./util.ts";

export interface TreeSpec {
  path: string;
  weight: number; // 1.0 for curated trees; <1 for legacy priors (doc 02)
}

export interface BootstrapResult {
  genre: GenreMap;
  labels: LabelMap;
  report: string;
  stats: { collections: number; artists: number; releases: number; unparsed: number };
}

function subdirs(dir: string): string[] {
  try {
    return readdirSync(dir)
      .sort()
      .filter((n) => !isJunkDir(n) && !n.startsWith(".") && statSync(join(dir, n)).isDirectory());
  } catch {
    return [];
  }
}

function hasFiles(dir: string): boolean {
  try {
    return readdirSync(dir).some((n) => !n.startsWith(".") && statSync(join(dir, n)).isFile());
  } catch {
    return false;
  }
}

export function bootstrapTrees(trees: TreeSpec[]): BootstrapResult {
  const artists: Record<string, Record<string, number>> = {};
  const labels: Record<string, Record<string, number>> = {};
  const grammarCounts: Record<string, number> = {};
  const unparsed: string[] = [];
  let releaseCount = 0;
  const collections = new Set<string>();

  const bump = (map: Record<string, Record<string, number>>, key: string, collection: string, w: number) => {
    const counts = map[key] ?? {};
    counts[collection] = round2((counts[collection] ?? 0) + w);
    map[key] = counts;
  };

  const countRelease = (collection: string, artist: string | null, dirName: string, w: number) => {
    const parsed = parseDirName(dirName);
    if (parsed) grammarCounts[parsed.grammar] = (grammarCounts[parsed.grammar] ?? 0) + 1;
    else if (unparsed.length < 30) unparsed.push(dirName);
    const who = artist ?? parsed?.artist;
    if (!who) return;
    releaseCount++;
    bump(artists, who, collection, w);
    if (parsed?.label) bump(labels, parsed.label, collection, w);
  };

  for (const tree of trees) {
    for (const collection of subdirs(tree.path)) {
      collections.add(collection);
      const collectionDir = join(tree.path, collection);
      for (const entry of subdirs(collectionDir)) {
        const entryDir = join(collectionDir, entry);
        const parsed = parseDirName(entry);
        if (parsed?.artist && parsed.album) {
          // Flat release dir directly under the collection.
          countRelease(collection, null, entry, tree.weight);
        } else if (/^\[.*\]$/.test(entry)) {
          // Slot dir ([Releases], [Compilations], ...) holding flat releases.
          for (const rel of subdirs(entryDir)) countRelease(collection, null, rel, tree.weight);
        } else {
          // Artist dir: subdirs are releases; flat files count as one release.
          const releases = subdirs(entryDir);
          for (const rel of releases) countRelease(collection, entry, rel, tree.weight);
          if (releases.length === 0 && hasFiles(entryDir)) {
            releaseCount++;
            bump(artists, entry, collection, tree.weight);
          }
        }
      }
    }
  }

  const lines = [
    "# Naming variants report",
    "",
    "Evidence for the naming-convention TBDs (doc 02). Generated by `intake bootstrap`.",
    "",
    "| grammar | releases |",
    "|---|---|",
    ...Object.entries(grammarCounts)
      .sort((a, b) => b[1] - a[1])
      .map(([g, n]) => `| ${g} | ${n} |`),
    "",
    `Unparsed release dir names: ${unparsed.length === 0 ? "none" : ""}`,
    ...unparsed.map((n) => `- \`${n}\``),
    "",
  ];

  return {
    genre: { artists, feedback: {}, aliases: {}, exceptions: [] },
    labels: { labels },
    report: lines.join("\n"),
    stats: {
      collections: collections.size,
      artists: Object.keys(artists).length,
      releases: releaseCount,
      unparsed: unparsed.length,
    },
  };
}
